name: Schedule BLS Dashboard

on:
  schedule:
    # Run at 12:00 PM UTC on the 15th of every month
    - cron: '0 12 15 * *'
  workflow_dispatch: # Allow manual triggers

jobs:
  run-dashboard:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Streamlit script with timeout
      - name: Run BLS Dashboard script with timeout
        run: |
          timeout 300 streamlit run app.py --server.headless true
        env:
          STREAMLIT_SERVER_PORT: 8501

      # Step 5: Log cleanup message
      - name: Cleanup
        if: always()
        run: |
          echo "Streamlit process has completed or timed out after 5 minutes."
